spring.application.name=labExam_3

spring.datasource.username=root
spring.datasource.password=root

#trainee.dao.type=jpa
#spring.profiles.active=Product
spring.profiles.active=dev

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:h2:mem:traineedb
spring.datasource.driver-class-name=org.h2.Driver


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console